services:
  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - matrix_net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - aggregator
    networks:
      - matrix_net

  splitter:
    build:
      context: ./splitter
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - worker
    networks:
      - matrix_net

networks:
  matrix_net:
    driver: bridge
